"""This code generated by ChatGPT on 2/1/2024 and is as yet untested.
"""
import imaplib
import email
import os

def download_attachments(email_address, password, search_criteria, save_folder):
    try:
        # Connect to Gmail server
        imap_server = imaplib.IMAP4_SSL('imap.gmail.com')
        
        # Login to your Gmail account
        imap_server.login(email_address, password)

        # Select the mailbox you want to search in (e.g., 'inbox')
        imap_server.select('inbox')

        # Search for emails matching the search criteria
        result, data = imap_server.search(None, search_criteria)

        if result == 'OK':
            email_ids = data[0].split()
            for email_id in email_ids:
                # Fetch the email by ID
                result, message_data = imap_server.fetch(email_id, '(RFC822)')
                if result == 'OK':
                    email_message = email.message_from_bytes(message_data[0][1])
                    subject = email_message["subject"]

                    # Check if the email has attachments
                    if email_message.get_content_maintype() == 'multipart':
                        for part in email_message.walk():
                            if part.get_content_maintype() == 'application' and part.get('Content-Disposition'):
                                attachment_name = part.get_filename()
                                if attachment_name:
                                    attachment_data = part.get_payload(decode=True)

                                    # Save the attachment to the specified folder
                                    save_path = os.path.join(save_folder, attachment_name)
                                    with open(save_path, 'wb') as attachment_file:
                                        attachment_file.write(attachment_data)
                                    print(f"Downloaded attachment: {attachment_name}")

        # Logout and close the connection
        imap_server.logout()
    
    except Exception as e:
        print(f"Error: {str(e)}")

# Example usage:
email_address = 'your_email@gmail.com'
password = 'your_password'
search_criteria = '(FROM "sender@example.com" SUBJECT "Your Subject" UNSEEN)'
save_folder = 'path_to_save_attachments'
download_attachments(email_address, password, search_criteria, save_folder)
